spring:
  application:
    name: springbootex07
  thymeleaf:
    cache: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger
server:
  port: 8081
